name: cellpose

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
    - torch
    - pyqtgraph
    - PyQt5
    - numpy (>=1.16.0)
    - numba
    - scipy
    - natsort