# for functions in bidcell/processing
# NOTE: Commented options default to None

cpus: 16 # number of CPUs for multiprocessing

files:
  data_dir: /ibex/user/iribarxm/spatial_transcriptomics/bidcell/BIDCell-main/breast_cancer_data/output # data directory for processed/output data
  fp_dapi: /ibex/user/iribarxm/spatial_transcriptomics/datasets/breast_data/morphology_mip.tif" # path of DAPI image or path of output stitched DAPI if using stitch_nuclei
  fp_transcripts: /ibex/user/iribarxm/spatial_transcriptomics/datasets/breast_data/breast_transcripts_formated_full.csv # path of transcripts file
  fp_ref: /ibex/user/iribarxm/spatial_transcriptomics/bidcell/BIDCell-main/breast_cancer_data/sc_references/sc_breast.csv # file path of reference data
  fp_pos_markers: /ibex/user/iribarxm/spatial_transcriptomics/bidcell/BIDCell-main/breast_cancer_data/sc_references/markers_pos.csv # file path of positive markers
  fp_neg_markers: /ibex/user/iribarxm/spatial_transcriptomics/bidcell/BIDCell-main/breast_cancer_data/sc_references/markers_neg.csv # file path of negative markers
  fp_selected_genes: /ibex/user/iribarxm/spatial_transcriptomics/bidcell/BIDCell-main/breast_cancer_data/sc_references/fp_selected_genes.txt # file containing names of genes to use

nuclei_fovs:
  stitch_nuclei_fovs: False # set True to stitch separate FOVs of DAPI together in 1 image

nuclei:
  #diameter: 30 # estimated diameter of nuclei for Cellpose - or None to automatically compute, default: None
  crop_nuclei_to_ts: True # crop nuclei to region of transcript detections - run generate_expression_maps() before segment_nuclei()

transcripts:
  shift_to_origin: True # shift to origin, making min(x) and min(y) (0,0)
  x_col: y # name of x location column in transcripts file
  y_col: x # name of y location column in transcripts file
  gene_col: geneID # name of genes column in transcripts file
  counts_col: MIDCounts # name of counts column in transcripts file, eg MIDCounts, default: None
  transcripts_to_filter: # genes starting with these strings will be filtered out
  - NegControlProbe_
  - antisense_
  - NegControlCodeword_
  - BLANK_
  - Blank-
  - NegPrb

affine:
  target_pix_um: 1.0 # microns per pixel to perform segmentation; default: 1.0
  base_pix_x: 1.0 # convert to microns along width by multiplying the original pixels by base_pix_x microns per pixel
  base_pix_y: 1.0 # convert to microns along width by multiplying the original pixels by base_pix_y microns per pixel
  base_ts_x: 1.0 # convert between transcript locations and target pixels along width
  base_ts_y: 1.0 # convert between transcript locations and target pixels along height
  global_shift_x: 0 # additional adjustment to align transcripts to DAPI in target pixels along image width; default: 0
  global_shift_y: 0 # additional adjustment to align transcripts to DAPI in target pixels along image height; default: 0

model_params:
  name: custom # segmentation model to use: custom for model in model.py or set to a encoder name from segmentation_models_pytorch; default: custom
  patch_size: 48 # size of transcriptomic image patches for input to DL model
  elongated: # list of elongated cell types that are in the single-cell reference
  - B-cells
  - CAFs
  - Cancer Epithelial
  - Endothelial
  - Myeloid
  - Normal Epithelial
  - PVL
  - Plasmablasts
  - T-cells

training_params:
  total_epochs: 1 # number of training epochs; default: 1
  total_steps: 200 # number of training steps; default: 4000
  ne_weight: 1.0 # weight for nuclei encapsulation loss; default: 1.0
  os_weight: 1.0 # weight for oversegmentation loss; default: 1.0
  cc_weight: 1.0 # weight for cell-calling loss; default: 1.0
  ov_weight: 1.0 # weight for oversegmentation loss; default: 1.0
  pos_weight: 1.0 # weight for positive marker loss; default: 1.0
  neg_weight: 1.0 # weight for negative marker loss; default: 1.0

testing_params:
  test_epoch: 1 # epoch to test; default: 1
  test_step: 200 # step number to test; default: 4000

experiment_dirs:
  dir_id: last # specify timestamp of output dir or leave blank to use latest dir, default: last